In [8]:
from skimage import io, data
import matplotlib.pyplot as plt
import numpy as np

In [9]:
a = np.array([[1,2,3],[4,5,6]],dtype=np.float32)
print(a)
print(a.ndim, a.shape, a.dtype)


[[1. 2. 3.]
 [4. 5. 6.]]
2 (2, 3) float32


## Zeros, Ones

In [10]:
M = np.ones((3,5))
print(M)
print(M.dtype)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
float64


## Arange

In [17]:
np.arange(1334, 1338)

array([1334, 1335, 1336, 1337])

## Concatenar

In [20]:
A = np.ones((2,3))
B = np.zeros((4,3))
np.concatenate([A,B])

array([[1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [24]:
A = np.ones((4,1))
B = np.zeros((4,2))
np.concatenate([A,B], axis=1)

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.]])

## Cast

In [14]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]], dtype=np.float32)
print(A)
print(a.astype(np.uint16))

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
[[1 2 3]
 [4 5 6]]


## Zeros_like e Ones_like

In [15]:
B = np.zeros_like(A)
print(B)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


## Valores aleatórios

In [16]:
np.random.random((4,2))

array([[0.18419989, 0.38937638],
       [0.79422283, 0.63894505],
       [0.44457307, 0.85812942],
       [0.78968775, 0.34584554]])

## Redimensão


In [17]:
a = np.array([1,2,3,4,5,6])
print(a)
a = a.reshape(3,2)
print(a)
a = a.reshape(2,-1)
print(a)
a = a.ravel()
print(a)

[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]]
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


## Operações matemáticas

In [18]:
a = np.array([1,2,3])
b= np.array([10,20,30])
a*b

array([10, 40, 90])

In [19]:
a > 2

array([False, False,  True])

In [20]:
np.sqrt(b)

array([3.16227766, 4.47213595, 5.47722558])